name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        default: 'latest'
        required: true
jobs:
  build:
    name: "Build lrclib:${{ github.event.inputs.tag }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "latest"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/garycraft/lrclib:${{ github.event.inputs.tag }}
